project:
  type: website
  output-dir: docs

website:
  title: "Satrio Adi Rukmono"
  navbar:
    left:
      - index.qmd
      - publications.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



