project:
  type: website
  output-dir: docs

website:
  title: "Satrio Adi Rukmono"
  favicon: favicon.png
  site-url: https://satrio.rukmono.id
  open-graph: true
  navbar:
    left:
      - index.qmd
      - publications.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



